name:  Continuous Deployment

on:
  push:
    branches:
      - 'main'    
      - 'master'    
      - 'release/**'    
      - 'prototype/**'    


jobs:
  build:
    strategy:
      matrix:
        Configuration: [v4, v5, v6]
    steps:
      - uses: actions/checkout@v3

