name:  Continuous Deployment

on:
  push:
    branches:
      - 'main'    
      - 'master'    
      - 'release/**'    
      - 'prototype/**'    


jobs:
  build:
    runs-on: ubuntu-latest     
    env:
      DOTNET_NOLOGO: '1'
      DOTNET_CLI_TELEMETRY_OPTOUT: '1'

    strategy:
      matrix:
        Configuration: [v4, v5, v6]

    steps:
      - uses: actions/checkout@v3

      - name: Add GitHub nuget feed
        run: | 
          dotnet nuget add source "https://nuget.pkg.github.com/unitycontainer/index.json" -n github -u unitycontainer -p ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text

      - name: Build
        env:
          VersionMajor: '${{ env.GitVersion_Major }}'
          VersionMinor: '${{ env.GitVersion_Minor }}'
          VersionPatch: '${{ env.GitVersion_Patch }}'
          Version: '${{ env.GitVersion_MajorMinorPatch }}'
          FileVersion: '${{ env.GitVersion_AssemblySemFileVer }}'
          PackageVersion: '${{ env.GitVersion_SemVer }}'
          AssemblyVersion: '${{ env.GitVersion_AssemblySemVer }}'
          InformationalVersion: '${{ env.GitVersion_InformationalVersion }}'
        run: | 
          dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True ${{ inputs.solution-path }}

      - name: Test
        run: | 
          dotnet test --no-restore --no-build --configuration Release ${{ inputs.solution-path }}


